//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class contenu
    {
        public int idContenu { get; set; }
        public Nullable<int> numj { get; set; }
        public Nullable<int> nump { get; set; }
        public Nullable<int> quantite { get; set; }
    
        public virtual jardin jardin { get; set; }
        public virtual Plante Plante { get; set; }
    }
}
