//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class jardin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jardin()
        {
            this.contenus = new HashSet<contenu>();
        }
    
        public int numJ { get; set; }
        public string nomJ { get; set; }
        public string Adresse { get; set; }
        public string ville { get; set; }
        public Nullable<int> superficier { get; set; }
        public Nullable<int> numjardinier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contenu> contenus { get; set; }
        public virtual jardinier jardinier { get; set; }
    }
}
